# Generated by Django 5.2.4 on 2026-03-07 15:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poc', '0025_remove_parsedemail_event_extraction_error_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('name', models.CharField(help_text='Name of the timeline', max_length=255, validators=[django.core.validators.RegexValidator(message='Timeline name must start with a letter and can only contain letters, numbers, spaces, underscores, or hyphens.', regex='^[a-zA-Z][\\w\\s-]+$')])),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether this timeline is active')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='poc.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'xbt_timelines',
                'ordering': ['-id'],
                'unique_together': {('case', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='The title of the timeline event', max_length=255)),
                ('description', models.TextField(help_text='A brief description of the timeline event')),
                ('event_date', models.DateTimeField(help_text='The date and time of the timeline event occurrence')),
                ('place', models.CharField(blank=True, help_text='Physical or virtual location of the timeline event', max_length=255)),
                ('data', models.JSONField(help_text='Original JSON returned by the LLM')),
                ('source_entity', models.CharField(choices=[('UPLOADED_FILE', 'Uploaded File'), ('PARSED_EMAIL', 'Parsed Email'), ('PARSED_EMAIL_ATTACHMENT', 'Parsed Email Attachment')], help_text='The entity from which this timeline event was extracted', max_length=50)),
                ('source_entity_id', models.PositiveIntegerField(help_text='ID of the source entity', validators=[django.core.validators.MinValueValidator(1)])),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.timeline')),
            ],
            options={
                'db_table': 'xbt_timeline_events',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TimelineExhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_exhibits', to='poc.uploadedfile')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibits', to='events.timeline')),
            ],
            options={
                'db_table': 'xbt_timeline_exhibits',
            },
        ),
        migrations.CreateModel(
            name='CandidateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_phrase', models.CharField(help_text='The action phrase that indicates the event', max_length=255)),
                ('raw_description', models.TextField(help_text='The raw description of the candidate event as extracted from the source')),
                ('event_date', models.DateTimeField(help_text='The date and time of the candidate event occurrence')),
                ('date_confidence', models.CharField(help_text='The confidence level of the event date extraction (e.g., explicit, inferred, weak)', max_length=50)),
                ('actors', models.JSONField(blank=True, default=list, help_text='A list of actors involved in the candidate event')),
                ('evidence_excerpt', models.TextField(help_text='An excerpt from the source that serves as evidence for the candidate event')),
                ('confidence', models.FloatField(help_text='The confidence score of the candidate event extraction (0.0 to 1.0)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('source', models.JSONField(default=dict, help_text='The source from which the candidate event was extracted (e.g., document, email or attachment and its metadata)')),
                ('timeline_exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_events', to='events.timelineexhibit')),
            ],
            options={
                'db_table': 'xbt_candidate_events',
                'ordering': ['-id'],
            },
        ),
    ]
