# Generated by Django 5.2.4 on 2026-02-04 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Event title', max_length=255)),
                ('description', models.TextField(help_text='A brief sentence containing details about trigger, participants, temporal & spatial anchors and attributes')),
                ('event_date', models.DateTimeField(help_text='Date and time of the event occurrence')),
                ('place', models.CharField(blank=True, help_text='Physical or virtual location of the event', max_length=255)),
                ('custom_title', models.CharField(blank=True, help_text='Custom title assigned by user', max_length=255)),
                ('custom_description', models.TextField(blank=True, help_text='Custom description assigned by user')),
                ('data', models.JSONField(help_text='Original JSON returned by the LLM')),
                ('source_entity', models.CharField(choices=[('UPLOADED_FILE', 'Uploaded File'), ('PARSED_EMAIL', 'Parsed Email'), ('PARSED_EMAIL_ATTACHMENT', 'Parsed Email Attachment')], help_text='The entity from which this event was extracted', max_length=50)),
                ('source_entity_id', models.PositiveIntegerField(help_text='ID of the source entity', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'xbt_events',
                'ordering': ['-event_date', '-created_at'],
                'indexes': [models.Index(fields=['source_entity', 'source_entity_id'], name='xbt_events_source__3b1e2e_idx'), models.Index(fields=['event_date'], name='xbt_events_event_d_ae9081_idx')],
            },
        ),
    ]
