# Generated by Django 5.2.4 on 2026-02-12 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('poc', '0024_rename_status_uploadedfile_embedding_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='poc.case'),
        ),
    ]
