# Generated by Django 5.2.4 on 2026-03-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_timeline_timelineevent_timelineexhibit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateevent',
            name='actors',
            field=models.JSONField(blank=True, default=list, help_text='A list of actors involved in the candidate event'),
        ),
    ]
