# Generated by Django 5.2.4 on 2026-03-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_candidateevent_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='status',
        ),
    ]
