networks:
  docket_ai-network:
    driver: bridge

services:
  docket_ai-django:
    build: .
    image: docket_ai-django
    container_name: docket_ai-django
    user: webinative
    command: python manage.py runserver 0:8000
    env_file:
      - docket_ai-django.env
      - .env
    volumes:
      - .:/home/webinative/code
      - docket_ai-django-vscode:/home/webinative/.vscode-server
    ports:
      - "8000:8000"
      - "3000:3000"
    networks:
      - docket_ai-network
    restart: on-failure:5

  docket_ai-postgres:
    image: pgvector/pgvector:pg16
    container_name: docket_ai-postgres
    environment:
      POSTGRES_USER: mravi
      POSTGRES_PASSWORD: mravi
      POSTGRES_DB: docket_ai
    volumes:
      - docket_ai-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - docket_ai-network

  docket_ai-mailhog:
    image: mailhog/mailhog
    container_name: docket_ai-mailhog
    logging:
      driver: "none" # disable logging
    ports:
      - "8025:8025" # web ui
    networks:
      - docket_ai-network
    restart: on-failure:5

  docket_ai-redis:
    image: redis:8.2-bookworm
    container_name: docket_ai-redis
    ports:
      - "6379:6379"
    networks:
      - docket_ai-network
    restart: on-failure:5

  docket_ai-celery:
    image: docket_ai-django
    container_name: docket_ai-celery
    user: webinative
    command: python -m celery -A docket_ai worker --loglevel=INFO
    env_file:
      - docket_ai-django.env
      - .env
    volumes:
      - .:/home/webinative/code
    depends_on:
      - docket_ai-redis
      - docket_ai-postgres
    networks:
      - docket_ai-network

volumes:
  docket_ai-django-vscode:
  docket_ai-postgres-data:
