[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]
[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "docket_ai.settings"
python_files = ["tests.py", "tests/*.py"]
[tool.djlint]
blank_line_after_tag = "extends,include,endblock"
max_blank_lines = 1
