# Generated by Django 5.2.4 on 2025-07-22 12:48

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_user_table"),
    ]

    operations = [
        VectorExtension(),
    ]
