# Generated by Django 5.2.4 on 2026-05-18 16:41

from django.db import migrations, models

import litigants.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="Litigant",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("name", models.CharField(max_length=255)),
                        ("bio", models.CharField(max_length=255)),
                        ("email", models.EmailField(blank=True, max_length=254)),
                        (
                            "phone",
                            models.CharField(
                                blank=True,
                                max_length=20,
                                validators=[litigants.validators.validate_phone_number],
                            ),
                        ),
                        ("address", models.TextField(blank=True)),
                        ("notes", models.TextField(blank=True)),
                    ],
                    options={
                        "db_table": "poc_litigants",
                    },
                ),
                migrations.CreateModel(
                    name="LitigantRole",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("name", models.CharField(max_length=255)),
                        ("handle", models.CharField(max_length=255, unique=True)),
                        ("description", models.TextField(blank=True, null=True)),
                    ],
                    options={
                        "db_table": "poc_litigant_roles",
                    },
                ),
            ],
            database_operations=[],
        )
    ]
