# Generated by Django 5.2.4 on 2025-07-28 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_on', models.DateTimeField()),
                ('sender', models.EmailField(max_length=254)),
                ('to_recipients', models.CharField()),
                ('cc_recipients', models.CharField(blank=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('cleaned_body', models.TextField()),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('embedding_error_message', models.TextField(blank=True, null=True)),
                ('uploaded_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_email', to='poc.uploadedfile')),
            ],
            options={
                'db_table': 'poc_parsed_emails',
            },
        ),
        migrations.CreateModel(
            name='ParsedEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='poc/uploaded_files/attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('embedding_error_message', models.TextField(blank=True, null=True)),
                ('parsed_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_attachments', to='poc.parsedemail')),
            ],
            options={
                'db_table': 'poc_parsed_email_attachments',
            },
        ),
    ]
