# Generated by Django 5.2.4 on 2025-07-28 11:06

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0002_parsedemail_parsedemailattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedEmailEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveSmallIntegerField()),
                ('chunk', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('parsed_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_email_embeddings', to='poc.parsedemail')),
            ],
            options={
                'db_table': 'poc_parsed_email_embeddings',
            },
        ),
    ]
