# Generated by Django 5.2.4 on 2025-07-30 09:54

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0003_parsedemailembedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parsedemailembedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=200, fields=['embedding'], m=16, name='parsed_email_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
