# Generated by Django 5.2.4 on 2025-08-05 08:24

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0004_parsedemailembedding_parsed_email_embedding_hnsw_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedEmailAttachmentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveSmallIntegerField()),
                ('chunk', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('parsed_email_attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_email_attachment_embeddings', to='poc.parsedemailattachment')),
            ],
            options={
                'db_table': 'poc_parsed_email_attachment_embeddings',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=200, fields=['embedding'], m=16, name='parsed_email_attachment_hnswidx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
