# Generated by Django 5.2.4 on 2025-08-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0005_parsedemailattachmentembedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='processed',
        ),
    ]
