# Generated by Django 5.2.4 on 2025-08-09 16:24

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0006_remove_uploadedfile_processed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parsedemailattachmentembedding',
            unique_together={('parsed_email_attachment', 'chunk_index')},
        ),
        migrations.AlterUniqueTogether(
            name='parsedemailembedding',
            unique_together={('parsed_email', 'chunk_index')},
        ),
        migrations.CreateModel(
            name='UploadedFileEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveSmallIntegerField()),
                ('chunk', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_file_embeddings', to='poc.uploadedfile')),
            ],
            options={
                'db_table': 'poc_uploaded_file_embeddings',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=200, fields=['embedding'], m=16, name='uploaded_file_mbdng_hnsw_idx', opclasses=['vector_cosine_ops'])],
                'unique_together': {('uploaded_file', 'chunk_index')},
            },
        ),
    ]
