# Generated by Django 5.2.4 on 2025-08-13 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0007_alter_parsedemailattachmentembedding_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Include the nature of dispute and summary of the conflict.', null=True)),
            ],
            options={
                'db_table': 'poc_cases',
            },
        ),
        migrations.CreateModel(
            name='Litigant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poc_litigants',
            },
        ),
        migrations.CreateModel(
            name='LitigantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'poc_litigant_roles',
            },
        ),
        migrations.CreateModel(
            name='CaseLitigant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_our_client', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_litigants', to='poc.case')),
                ('litigant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_litigants', to='poc.litigant')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_litigants', to='poc.litigantrole')),
            ],
            options={
                'db_table': 'poc_case_litigants',
                'unique_together': {('case', 'litigant')},
            },
        ),
        migrations.AddField(
            model_name='case',
            name='litigants',
            field=models.ManyToManyField(related_name='cases', through='poc.CaseLitigant', to='poc.litigant'),
        ),
    ]
