# Generated by Django 5.2.4 on 2025-08-13 16:23

from django.db import migrations


def _get_roles():
    return [
        ("Plaintiff", "PLAINTIFF", None),
        ("Third-party Plaintiff", "THIRD_PARTY_PLAINTIFF", None),
        ("Defendant", "DEFENDANT", None),
        ("Third-party Defendant", "THIRD_PARTY_DEFENDANT", None),
        ("Witness", "WITNESS", None),
    ]


def create_litigant_roles(apps, schema_editor):
    LitigantRole = apps.get_model("poc", "LitigantRole")
    roles = _get_roles()
    for name, handle, description in roles:
        LitigantRole.objects.get_or_create(
            handle=handle, defaults={"name": name, "description": description}
        )


def reverse_create_litigant_roles(apps, schema_editor):
    LitigantRole = apps.get_model("poc", "LitigantRole")
    roles = _get_roles()
    for name, handle, description in roles:
        LitigantRole.objects.filter(handle=handle).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("poc", "0008_case_litigant_litigantrole_caselitigant_and_more"),
    ]

    operations = [
        migrations.RunPython(create_litigant_roles, reverse_create_litigant_roles),
    ]
