# Generated by Django 5.2.4 on 2025-08-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0009_create_litigant_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
