# Generated by Django 5.2.4 on 2025-08-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0011_chatthread_chatmessage_threadmemory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, default='', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Include the nature of dispute and summary of the conflict.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='litigant',
            name='address',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='litigant',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='litigant',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='litigant',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parsedemail',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parsedemail',
            name='cc_recipients',
            field=models.CharField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parsedemail',
            name='embedding_error_message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parsedemailattachment',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parsedemailattachment',
            name='embedding_error_message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='error_message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
