# Generated by Django 5.2.4 on 2025-08-25 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0012_alter_case_case_number_alter_case_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_threads', to='poc.case'),
        ),
    ]
