# Generated by Django 5.2.4 on 2025-08-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0013_chatthread_case'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThreadMemory',
        ),
    ]
