# Generated by Django 5.2.4 on 2025-09-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0014_delete_threadmemory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
