# Generated by Django 5.2.4 on 2025-11-03 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0015_alter_case_case_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='poc.case'),
            preserve_default=False,
        ),
    ]
