# Generated by Django 5.2.4 on 2025-11-03 16:56

import poc.models
import poc.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0016_uploadedfile_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=poc.models.get_file_upload_path, validators=[poc.validators.FileValidator(allowed_mime_types=['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'text/plain', 'text/csv', 'application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-powerpoint', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', 'message/rfc822'], max_size_mb=10)]),
        ),
    ]
