# Generated by Django 5.2.4 on 2025-12-05 14:07

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0017_uploadedfile_filename_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='exhibit_code',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Can only contain uppercase letters, numbers, and special characters - / . ( ). Must start with a letter and end with a number or ).', regex='^[A-Z][A-Z0-9-/.()]*[1-9)]$')]),
        ),
        migrations.AlterUniqueTogether(
            name='uploadedfile',
            unique_together={('case', 'exhibit_code')},
        ),
    ]
