# Generated by Django 5.2.4 on 2025-12-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0018_uploadedfile_exhibit_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
