# Generated by Django 5.2.4 on 2026-01-08 06:16

import poc.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0019_uploadedfile_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[poc.validators.validate_phone_number]),
        ),
    ]
