# Generated by Django 5.2.4 on 2026-02-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0020_alter_litigant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedemailattachment',
            name='event_extraction_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parsedemailattachment',
            name='event_extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('extracted', 'Extracted'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
