# Generated by Django 5.2.4 on 2026-02-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0021_parsedemailattachment_event_extraction_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedemail',
            name='event_extraction_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parsedemail',
            name='event_extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('extracted', 'Extracted'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='event_extraction_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='event_extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('extracted', 'Extracted'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
