# Generated by Django 5.2.4 on 2026-02-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0022_parsedemail_event_extraction_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsedemail',
            name='embedding_error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='parsedemail',
            name='event_extraction_error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='parsedemailattachment',
            name='embedding_error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='parsedemailattachment',
            name='event_extraction_error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='event_extraction_error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
