# Generated by Django 5.2.4 on 2026-02-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0023_alter_parsedemail_embedding_error_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='status',
            new_name='embedding_status',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='error_message',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='embedding_error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
