# Generated by Django 5.2.4 on 2026-03-03 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0024_rename_status_uploadedfile_embedding_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedemail',
            name='event_extraction_error_message',
        ),
        migrations.RemoveField(
            model_name='parsedemail',
            name='event_extraction_status',
        ),
        migrations.RemoveField(
            model_name='parsedemailattachment',
            name='event_extraction_error_message',
        ),
        migrations.RemoveField(
            model_name='parsedemailattachment',
            name='event_extraction_status',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='event_extraction_error_message',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='event_extraction_status',
        ),
    ]
