# Generated by Django 5.2.4 on 2026-05-18 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("poc", "0025_remove_parsedemail_event_extraction_error_message_and_more"),
        ("litigants", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="Litigant",
                ),
                migrations.DeleteModel(
                    name="LitigantRole",
                ),
            ],
            database_operations=[],
        )
    ]
