# Generated by Django 5.2.4 on 2026-05-20 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0001_initial"),
        ("events", "0002_alter_timeline_case"),
        ("poc", "0026_delete_litigant_delete_litigantrole"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="chatthread",
                    name="case",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_threads",
                        to="cases.case",
                    ),
                ),
                migrations.RemoveField(
                    model_name="caselitigant",
                    name="case",
                ),
                migrations.AlterField(
                    model_name="uploadedfile",
                    name="case",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to="cases.case",
                    ),
                ),
                migrations.AlterUniqueTogether(
                    name="caselitigant",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="caselitigant",
                    name="litigant",
                ),
                migrations.RemoveField(
                    model_name="caselitigant",
                    name="role",
                ),
                migrations.DeleteModel(
                    name="Case",
                ),
                migrations.DeleteModel(
                    name="CaseLitigant",
                ),
            ],
            database_operations=[],
        )
    ]
